#spring.application.name=animal-service

server.port=8085

#Propriedade do bando de dados
spring.datasource.url=jdbc:h2:mem:db-animais
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=none

# spring.data.source.url=h2:file/ebac/animais